# 置換変数
substitutions:
  _PROJECT_ID: "portfolio-dex-dev"
  _REPO: "portfolio-docker-dev" # _PROJECT_ID に依存しない文字列
  _IMAGE_TAG: "local" # Pull Request ビルドなど

steps:
  # Bento
  - id: "Build & Push Bento"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/bento:${_IMAGE_TAG}",
        "--push",
        "-f",
        "docker/bento/Dockerfile",
        ".",
      ]

  # Streamlit
  - id: "Build & Push Streamlit"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/streamlit:${_IMAGE_TAG}",
        "--push",
        "-f",
        "docker/streamlit/Dockerfile",
        ".",
      ]

  # MLflow
  - id: "Build & Push MLflow"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/mlflow:${_IMAGE_TAG}",
        "--push",
        "-f",
        "docker/mlflow/Dockerfile",
        ".",
      ]

# 成果物 URI
images:
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/bento:${_IMAGE_TAG}"
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/streamlit:${_IMAGE_TAG}"
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/mlflow:${_IMAGE_TAG}"
