substitutions:
  _ENV: "" # dev / prod
  _REPO: "" # portfolio-docker-${_ENV}
  _PROJECT_ID: "" # GCP プロジェクト ID
  _TF_SA_EMAIL: "" # Terraform 用サービスアカウント
  _ARTIFACTS_BUCKET: "" # MLflow artifacts 用 GCS バケット

steps:
  # 1) Docker イメージをビルドして GCP Artifact Registry へプッシュ
  # Bento
  - id: "Build & Push Bento"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/bento:$BUILD_ID",
        "--push",
        "-f",
        "docker/bento/Dockerfile",
        ".",
      ]

  # Streamlit
  - id: "Build & Push Streamlit"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/streamlit:$BUILD_ID",
        "-f",
        "docker/streamlit/Dockerfile",
        ".",
      ]

  # MLflow
  - id: "Build & Push MLflow"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64",
        "-t",
        "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/mlflow:$BUILD_ID",
        "-f",
        "docker/mlflow/Dockerfile",
        ".",
      ]

  # 2) Terraform 初期化
  - id: "Terraform Init"
    name: "hashicorp/terraform:1.11.4"
    entrypoint: "sh"
    args: [
        "-c",
        "cd infra/envs/${_ENV} && \
        terraform init \
        -backend-config=bucket=terraform-state-portfolio-dex \
        -backend-config=prefix=${_ENV}",
        -reconfigure",
      ]

  # 3) Terraform Plan
  - id: "Terraform Plan"
    name: "hashicorp/terraform:1.11.4"
    args:
      [
        "-chdir=infra/envs/${_ENV}",
        "plan",
        "-var=project_id=${_PROJECT_ID}",
        "-var=tf_service_account_email=${_TF_SA_EMAIL}",
        "-var=env=${_ENV}",
        "-var=artifacts_bucket=${_ARTIFACTS_BUCKET}",
        "-var=image_tag=${BUILD_ID}",
        "-out=tfplan",
        "-input=false",
      ]

  # 4) Terraform Apply (main ブランチ or prod タグの場合のみ)
  - id: "Terraform Apply"
    name: "hashicorp/terraform:1.11.4"
    args:
      [
        "-chdir=infra/envs/${_ENV}",
        "apply",
        "-var=project_id=${_PROJECT_ID}",
        "-var=tf_service_account_email=${_TF_SA_EMAIL}",
        "-var=env=${_ENV}",
        "-var=artifacts_bucket=${_ARTIFACTS_BUCKET}",
        "-var=image_tag=${BUILD_ID}",
        "-out=tfplan",
        "-input=false",
        "-auto-approve",
        "tfplan",
      ]

images:
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/bento:$BUILD_ID"
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/streamlit:$BUILD_ID"
  - "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/mlflow:$BUILD_ID"
