services:
  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./protocols.yml:/opt/airflow/dags/protocols.yml
      - ./:/opt/airflow/project
      - ./mlruns:/app/mlruns
    env_file:
      - .env
    environment:
      GIT_PYTHON_REFRESH: quiet
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_SNOWFLAKE_DEFAULT: >-
        snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@/${SNOWFLAKE_DATABASE}/${SNOWFLAKE_SCHEMA}?account=${SNOWFLAKE_ACCOUNT}&warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PYTHONPATH: /opt/airflow/project
  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns/artifacts:/app/mlruns/artifacts
      - ./mlruns/db:/app/mlruns/db
  bento:
    build:
      context: .
      dockerfile: docker/bento/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - bentoml_models:/root/.bentoml/models
      - ./mlruns:/app/mlruns
    depends_on:
      - mlflow
  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit/Dockerfile
    volumes:
      - ./app:/app:cached
    ports:
      - "8501:8501"
    environment:
      - BENTO_API_URL=http://bento:3000/predict
    env_file:
      - .env
    depends_on:
      - bento

volumes:
  bentoml_models:
