FROM apache/airflow:3.0.0-python3.11

# ---------- Snowflake プロバイダーをインストール ----------
RUN pip install --no-cache-dir \
  "apache-airflow-providers-snowflake>=5.3.1,<6.0.0" \
  "dbt-core==1.8.0" \
  "dbt-snowflake==1.8.0" \
  "dbt-duckdb==1.9.3"
