services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./protocols.yml:/opt/airflow/dags/protocols.yml
      - ./:/opt/airflow/project
      - ./mlruns:/opt/mlflow/mlruns
    env_file:
      - .env
    environment:
      GIT_PYTHON_REFRESH: quiet
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CONN_SNOWFLAKE_DEFAULT: >-
        snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@/${SNOWFLAKE_DATABASE}/${SNOWFLAKE_SCHEMA}?account=${SNOWFLAKE_ACCOUNT}&warehouse=${SNOWFLAKE_WAREHOUSE}&role=${SNOWFLAKE_ROLE}
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PYTHONPATH: /opt/airflow/project
  mlflow:
    image: python:3.11-slim
    command:
      - sh
      - -c
      - |
        pip install --no-cache-dir mlflow &&
        mlflow server \
          --backend-store-uri sqlite:////opt/mlflow/mlruns/mlflow.db \
          --default-artifact-root file:///opt/mlflow/mlruns/artifacts \
          --host 0.0.0.0 \
          --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns/artifacts:/opt/mlflow/mlruns/artifacts
      - ./mlruns/db:/opt/mlflow/mlruns/db
  bento:
    build:
      context: .
      dockerfile: Dockerfile.bento
    ports:
      - "3000:3000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - bentoml_models:/root/.bentoml/models
      - ./mlruns:/opt/mlflow/mlruns
    depends_on:
      - mlflow

volumes:
  bentoml_models:
