dex_bigquery:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /tmp/dev.duckdb

    sf:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: ETL_WH
      database: DEX_RAW
      schema: RAW
      threads: 4
