-- ロールの使用
USE ROLE ACCOUNTADMIN;

-- WAREHOUSE の作成
CREATE WAREHOUSE IF NOT EXISTS ETL_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- DATABASE の作成
CREATE DATABASE IF NOT EXISTS DEX_RAW;

-- DATABASE の使用
USE DATABASE DEX_RAW;

-- SCHEMA の作成
CREATE SCHEMA IF NOT EXISTS RAW;