-- ロールの使用
USE ROLE ACCOUNTADMIN;

-- DATABASE の使用
USE DATABASE DEX_RAW;

-- ETL用ロール作成
CREATE ROLE IF NOT EXISTS ETL_ROLE;

-- ロールへの権限付与
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE ETL_ROLE;

-- DATABASE への権限付与
GRANT USAGE ON DATABASE DEX_RAW TO ROLE ETL_ROLE;

-- SCHEMA への権限付与  
GRANT USAGE ON SCHEMA RAW TO ROLE ETL_ROLE;

-- dbtにビュー作成権限を付与
GRANT
CREATE VIEW
  ON SCHEMA RAW TO ROLE ETL_ROLE;

-- dbtにテーブル作成権限を付与
GRANT
CREATE TABLE
  ON SCHEMA RAW TO ROLE ETL_ROLE;

-- ユーザーへのロール割当
GRANT ROLE ETL_ROLE TO USER KOSAKI08;

-- mart_pool_features テーブルへの SELECT 権限を ETL_ROLE に付与
GRANT
SELECT
  ON TABLE RAW.mart_pool_features TO ROLE ETL_ROLE;

-- すでにあるテーブルすべてへの SELECT
GRANT
SELECT
  ON ALL TABLES IN SCHEMA RAW TO ROLE ETL_ROLE;

-- 将来作成されるテーブルにも自動で SELECT を付与
GRANT
SELECT
  ON FUTURE TABLES IN SCHEMA RAW TO ROLE ETL_ROLE;

-- MART_POOL_FEATURES テーブルへの SELECT 権限を ETL_ROLE に付与
GRANT
SELECT
  ON TABLE DEX_RAW.RAW.MART_POOL_FEATURES TO ROLE ETL_ROLE;