-- ロールの使用
USE ROLE ACCOUNTADMIN;

-- DATABASE の使用
USE DATABASE DEX_RAW;

-- ETL用ロール作成
CREATE ROLE IF NOT EXISTS ETL_ROLE;

-- ロールへの権限付与
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE ETL_ROLE;

-- DATABASE への権限付与
GRANT USAGE ON DATABASE DEX_RAW TO ROLE ETL_ROLE;

-- SCHEMA への権限付与
GRANT USAGE ON SCHEMA RAW TO ROLE ETL_ROLE;

-- ユーザーへのロール割当
GRANT ROLE ETL_ROLE TO USER KOSAKI08;