-- ロールの使用
USE ROLE ACCOUNTADMIN;

-- DATABASE の使用
USE DATABASE DEX_RAW;

-- SCHEMA の使用
USE SCHEMA RAW;

-- JSONL 用ファイルフォーマット
CREATE FILE FORMAT IF NOT EXISTS JSONL_FMT TYPE = 'JSON' COMPRESSION = 'AUTO';

-- 内部ステージ
CREATE STAGE IF NOT EXISTS DEX_STAGE FILE_FORMAT = JSONL_FMT;