name: CI/CD via Cloud Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cloud_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2) gcloud CLI をセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3) Cloud Build をトリガー
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_ENV="dev",_REPO="portfolio-docker-dev" \
            .
