name: CI/CD via Cloud Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  cloud_build:
    runs-on: ubuntu-latest

    env:
      ENV: dev
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      TF_SA_EMAIL: ${{ secrets.TF_SA_EMAIL }}
      ARTIFACTS_BUCKET: ${{ secrets.ARTIFACTS_BUCKET }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: tf-svc@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          audience: "https://github.com/${{ github.repository }}"

      # 3) gcloud CLI をセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      # 4) Cloud Build をトリガー
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions="_ENV=dev,_REPO=portfolio-docker-dev,_PROJECT_ID=$PROJECT_ID,_TF_SA_EMAIL=$TF_SA_EMAIL,_ARTIFACTS_BUCKET=$ARTIFACTS_BUCKET" \
            .
