name: CI/CD via Cloud Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cloud_build:
    runs-on: ubuntu-latest

    env:
      ENV: dev
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      TF_SA_EMAIL: ${{ secrets.TF_SA_EMAIL }}
      ARTIFACTS_BUCKET: ${{ secrets.ARTIFACTS_BUCKET }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3) gcloud CLI をセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      # 4) Cloud Build をトリガー
      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions="_ENV=dev,_REPO=portfolio-docker-dev,_PROJECT_ID=$PROJECT_ID,_TF_SA_EMAIL=$TF_SA_EMAIL,_ARTIFACTS_BUCKET=$ARTIFACTS_BUCKET" \
            .

      # 5) Terraform のセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 6) Terraform 初期化
      - name: Terraform Init
        working-directory: infra/envs/${{ env.ENV }}
        run: terraform init \
          -backend-config="bucket=terraform-state-portfolio-dex" \
          -backend-config="prefix=${{ env.ENV }}"

      # 7) Terraform Plan
      - name: Terraform Plan
        working-directory: infra/envs/${{ env.ENV }}
        run: |
          terraform plan -out=tfplan \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="tf_service_account_email=${{ env.TF_SA_EMAIL }}" \
            -var="env=${{ env.ENV }}" \
            -var="artifacts_bucket=${{ env.ARTIFACTS_BUCKET }}" \
            -var="image_tag=${{ env.IMAGE_TAG }}"

      # 8) Terraform Apply
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/envs/${{ env.ENV }}
        run: terraform apply -auto-approve tfplan
