name: Sync DAGs to Composer

on:
  push:
    branches: [dev, main]
    paths: ["dags/**"]

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: tf-svc@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          audience: https://github.com/${{ github.repository }}

      # 3) gcloud CLI をセットアップ
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      # 4) DAGs の同期
      - name: Upload DAGs
        run: |
          ENV=${{ matrix.env }}
          gcloud composer environments storage dags import \
            --environment dex-airflow-${ENV} \
            --location asia-northeast1 \
            --source dags/
