# dev への自動デプロイ用
name: "Terraform Apply (dev)"

on:
  push:
    branches: [dev]
    paths: ["infra/**"]

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-dev-apply
      cancel-in-progress: false # デプロイ中はキャンセルしない
    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Terraform をセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      # 3) Terraform の初期化
      - name: Initialize Terraform
        run: terraform -chdir=infra init

      # 4) Terraform の適用
      - name: Apply Terraform
        run: terraform -chdir=infra apply \
          -input=false -auto-approve \
          -lock-timeout=300s
