# prod への手動デプロイ用
name: "Terraform Apply (prod)"

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: terraform-prod-apply
      cancel-in-progress: false # デプロイ中はキャンセルしない
    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Terraform をセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 3) Terraform の初期化
      - name: Initialize Terraform
        run: terraform -chdir=infra init

      # 4) Terraform の適用
      - name: Apply Terraform
        run: terraform -chdir=infra apply \
          -input=false -auto-approve \
          -lock-timeout=300s
