# dev への自動デプロイ用
name: "Terraform Apply (dev)"

# パーミッション設定
permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [dev]
    paths: ["infra/**"]

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-dev-apply
      cancel-in-progress: false # デプロイ中はキャンセルしない
    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: tf-svc@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
          audience: https://github.com/${{ github.repository }}

      # 3) Terraform をセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      # 4) Terraform の初期化
      - name: Initialize Terraform
        run: terraform -chdir=infra init

      # 5) Terraform の適用
      - name: Apply Terraform
        run: terraform -chdir=infra apply -input=false -auto-approve -lock-timeout=300s
